### ISSUE TITLE
ios 测试 alipay_kit   出现 如下错误 没有导入 alipay_kit_ios 

### ISSUE THREAD

**Issue by writewhite** [v7lin/fake_alipay#51]
Unhandled Exception: MissingPluginException(No implementation found for method isInstalled on channel v7lin.github.io/alipay_kit)

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method isInstalled on channel v7lin.github.io/alipay_kit)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
<asynchronous suspension>
#1      MethodChannelAlipayKit.isInstalled (package:alipay_kit/src/alipay_kit_method_channel.dart:46:12)
<asynchronous suspension>
#2      _HomeState.build.<anonymous closure> (package:alipay_kit_example/main.dart:85:30)
<asynchronous suspension>

**Comment by droplet-js** [comment]
你都知道问题了 … 还提 issue 干啥 …

**Comment by writewhite** [comment]
> 你都知道问题了 … 还提 issue 干啥 …

我只是要用支付宝授权登录，没有要用支付 
alipay_kit_ios 是为了支付宝支付

**Comment by droplet-js** [comment]
> > 你都知道问题了 … 还提 issue 干啥 …
> 
> 
> 
> 我只是要用支付宝授权登录，没有要用支付 
> 
> alipay_kit_ios 是为了支付宝支付

那你找错地方了，iOS的sdk是包含登录和支付的，不是分开的 … 你自己去支付宝那边找找有没有其他的方案 …

**Comment by InTheClodus** [comment]
他的插件是分开写的，然后在总的插件里，只引入了安卓的，没有引入ios的

**Comment by sunjianan9900** [comment]
因为ios引入支付宝的sdk严重就会被封号，被当作隐藏支付。
所以不引入ios支付是为了你的安全。
你只想登录的话就用其他的包

**Comment by moosoul** [comment]
> 因为ios引入支付宝的sdk严重就会被封号，被当作隐藏支付。 所以不引入ios支付是为了你的安全。 你只想登录的话就用其他的包

可以细说一下封号么？这个封号是指的封我们的商户号？

**Comment by sunjianan9900** [comment]
> > 因为ios引入支付宝的sdk严重就会被封号，被当作隐藏支付。 所以不引入ios支付是为了你的安全。 你只想登录的话就用其他的包
> 
> 可以细说一下封号么？这个封号是指的封我们的商户号？

当然是指的苹果开发者账号（谷歌也是）
但是你如果有充足的理由引入支付宝也是可以的，例如你是实体销售（比如淘宝，pdd那种App）但是使用支付宝支付购买会员、虚拟产品类是一定封号的，绕过iap
